[book]
authors = ["Sovereign Labs <info@sovereign.xyz>"]
language = "en"
multilingual = false
src = "src"
title = "The Sovereign SDK Book"

[output.html]
# default-theme = "sovereign-dark"
# preferred-dark-theme = "sovereign-dark"
mathjax-support = true
cname = "docs.sovereign.xyz"