[book]
authors = ["Sovereign Labs <info@sovereign.xyz>"]
language = "en"
src = "src"
title = "The Sovereign SDK Book"

[output.html]
mathjax-support = true
cname = "docs.sovereign.xyz"
default-theme = "sovereign-dark"
preferred-dark-theme = "sovereign-dark"
additional-css = [
  "theme/css/sovereign-dark.css",
  "theme/assets/sovereign-dark-highlight.css",
]

[output.html.playpen]
copyable = true
editable = false
runnable = false
